#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/piano

PRODUCT_COPY_FILES += \
    vendor/xiaomi/piano/proprietary/odm/etc/df_default.xml:$(TARGET_COPY_OUT_ODM)/etc/df_default.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/init.panel_info.sh:$(TARGET_COPY_OUT_ODM)/etc/init.panel_info.sh \
    vendor/xiaomi/piano/proprietary/odm/etc/init/android.hardware.weaver.rc:$(TARGET_COPY_OUT_ODM)/etc/init/android.hardware.weaver.rc \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b00 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b01 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b02 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b03 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b04 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b05 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b06 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b07 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b08 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b09 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b10 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b11 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b12 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b13 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b14 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b15 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b16 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b17 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b18 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b19 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b20 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.mdt \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b00:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b00 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b01:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b01 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b02:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b02 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b03:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b03 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b04:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b04 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b05:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b05 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b06:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b06 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b07:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b07 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b08:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b08 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b09:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b09 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b10:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b10 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b11:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b11 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b12:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b12 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b13:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b13 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b14:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b14 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b15:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b15 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b16:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b16 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b17:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b17 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b18:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b18 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b19:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b19 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b20:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b20 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.mbn:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.mdt:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.mdt \
    vendor/xiaomi/piano/proprietary/odm/firmware/MCU_Upgrade.bin:$(TARGET_COPY_OUT_ODM)/firmware/MCU_Upgrade.bin \
    vendor/xiaomi/piano/proprietary/odm/firmware/MP_Setting_Criteria_59B0.csv:$(TARGET_COPY_OUT_ODM)/firmware/MP_Setting_Criteria_59B0.csv \
    vendor/xiaomi/piano/proprietary/odm/firmware/MP_Setting_Criteria_59BB.csv:$(TARGET_COPY_OUT_ODM)/firmware/MP_Setting_Criteria_59BB.csv \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b00:$(TARGET_COPY_OUT_ODM)/firmware/evass.b00 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b01:$(TARGET_COPY_OUT_ODM)/firmware/evass.b01 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b02:$(TARGET_COPY_OUT_ODM)/firmware/evass.b02 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b03:$(TARGET_COPY_OUT_ODM)/firmware/evass.b03 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b04:$(TARGET_COPY_OUT_ODM)/firmware/evass.b04 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b05:$(TARGET_COPY_OUT_ODM)/firmware/evass.b05 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b06:$(TARGET_COPY_OUT_ODM)/firmware/evass.b06 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b07:$(TARGET_COPY_OUT_ODM)/firmware/evass.b07 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b08:$(TARGET_COPY_OUT_ODM)/firmware/evass.b08 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b09:$(TARGET_COPY_OUT_ODM)/firmware/evass.b09 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b10:$(TARGET_COPY_OUT_ODM)/firmware/evass.b10 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b11:$(TARGET_COPY_OUT_ODM)/firmware/evass.b11 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b12:$(TARGET_COPY_OUT_ODM)/firmware/evass.b12 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b13:$(TARGET_COPY_OUT_ODM)/firmware/evass.b13 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b14:$(TARGET_COPY_OUT_ODM)/firmware/evass.b14 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b15:$(TARGET_COPY_OUT_ODM)/firmware/evass.b15 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b16:$(TARGET_COPY_OUT_ODM)/firmware/evass.b16 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b17:$(TARGET_COPY_OUT_ODM)/firmware/evass.b17 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b18:$(TARGET_COPY_OUT_ODM)/firmware/evass.b18 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b19:$(TARGET_COPY_OUT_ODM)/firmware/evass.b19 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.mbn:$(TARGET_COPY_OUT_ODM)/firmware/evass.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.mdt:$(TARGET_COPY_OUT_ODM)/firmware/evass.mdt \
    vendor/xiaomi/piano/proprietary/odm/firmware/film_model.tflite:$(TARGET_COPY_OUT_ODM)/firmware/film_model.tflite \
    vendor/xiaomi/piano/proprietary/odm/firmware/fs19xx.fsm:$(TARGET_COPY_OUT_ODM)/firmware/fs19xx.fsm \
    vendor/xiaomi/piano/proprietary/odm/firmware/gen80000_zap.mbn:$(TARGET_COPY_OUT_ODM)/firmware/gen80000_zap.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/novatek_nt36532_piano_fw_boe.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_piano_fw_boe.bin \
    vendor/xiaomi/piano/proprietary/odm/firmware/novatek_nt36532_piano_fw_csot.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_piano_fw_csot.bin \
    vendor/xiaomi/piano/proprietary/odm/firmware/novatek_nt36532_piano_mp_boe.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_piano_mp_boe.bin \
    vendor/xiaomi/piano/proprietary/odm/firmware/novatek_nt36532_piano_mp_csot.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_piano_mp_csot.bin \
    vendor/xiaomi/piano/proprietary/odm/firmware/nvt_run_selftest_get_result_data_sample.bat:$(TARGET_COPY_OUT_ODM)/firmware/nvt_run_selftest_get_result_data_sample.bat \
    vendor/xiaomi/piano/proprietary/odm/firmware/palm_check.tflite:$(TARGET_COPY_OUT_ODM)/firmware/palm_check.tflite \
    vendor/xiaomi/piano/proprietary/odm/firmware/piano_nova_boe_thp_config.ini:$(TARGET_COPY_OUT_ODM)/firmware/piano_nova_boe_thp_config.ini \
    vendor/xiaomi/piano/proprietary/odm/firmware/piano_nova_csot_thp_config.ini:$(TARGET_COPY_OUT_ODM)/firmware/piano_nova_csot_thp_config.ini \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu30_2v.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu30_2v.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu30_2v_unsigned.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu30_2v_unsigned.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu33_4v.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu33_4v_unsigned.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu33_4v_unsigned.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu35_4v.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu35_4v.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu35_4v_unsigned.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu35_4v_unsigned.mbn \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/DPU1010.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU1010.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/DPU10__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU10__.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/DPU11__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU11__.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/DPU12__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU12__.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/DPU9__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU9__.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/camera_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/camera_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/cpu_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/cpu_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/default_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/default_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/display_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/display_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/formats.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/formats.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/graphics_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/graphics_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/pipe_config_DPU11__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/pipe_config_DPU11__.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_1x_y1280x720.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_1x_y1280x720.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_1x_y720x1280.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_1x_y720x1280.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_2x_y1280x720.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_2x_y1280x720.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_2x_y544x960.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_2x_y544x960.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_2x_y720x1280.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_2x_y720x1280.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_2x_y960x544.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_2x_y960x544.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_3x_y384x640.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_3x_y384x640.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_3x_y640x384.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_3x_y640x384.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/thermallevel_to_fps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/thermallevel_to_fps.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/ubwc_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/ubwc_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/video_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/video_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/displayconfig/display_id_4630946916234099603.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630946916234099603.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/displayconfig/display_id_4630947039571902850.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630947039571902850.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/displayconfig/display_id_4630947039571902851.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630947039571902851.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/displayconfig/display_id_4630947075271898515.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630947075271898515.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/displayconfig/display_layout_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_layout_configuration.xml \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen70900_aqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_aqe.fw \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen70900_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_sqe.fw \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen70900_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_zap.mbn \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen70e00_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70e00_sqe.fw \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen70e00_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70e00_zap.mbn \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen71700_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gen71700_gmu.bin \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen80000_aqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen80000_aqe.fw \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen80000_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gen80000_gmu.bin \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen80000_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen80000_sqe.fw \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen80600_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gen80600_gmu.bin \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gmu_gen70900.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70900.bin

PRODUCT_PACKAGES += \
    displayfeature.default \
    libMiDispDevManager \
    libadaptivehdr \
    libclient2slpi.notifier \
    libcolortempmode \
    libdisplaycount \
    libdisplaylog \
    libdither \
    libeyecare \
    libflatmode \
    libfpsmonitor \
    libhistprocess \
    libmi-stc-HW-modulate \
    libmiBrightness \
    libmiClstc \
    libmiSensorCtrl \
    libmiXmlParser \
    libmi_dspp \
    libmi_weaver \
    libmieventnodewatch \
    libpaperMode \
    librhytheyecare \
    libsdr2hdr \
    libsre \
    libtruetone \
    libvideomode \
    android.hardware.weaver.xml \
    vendor.xiaomi.hw.touchfeature-service.xml \
    android.hardware.weaver \
    vendor.xiaomi.hw.touchfeature-service \
    toucheventcheck
