#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/piano

PRODUCT_COPY_FILES += \
    vendor/xiaomi/piano/proprietary/odm/etc/init/init.cirrus.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.cirrus.rc \
    vendor/xiaomi/piano/proprietary/odm/etc/init/init.foursemi.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.foursemi.rc \
    vendor/xiaomi/piano/proprietary/odm/etc/init/init.tfa.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.tfa.rc \
    vendor/xiaomi/piano/proprietary/odm/etc/init/init.xiaomi_hall.rc:$(TARGET_COPY_OUT_ODM)/etc/init/init.xiaomi_hall.rc \
    vendor/xiaomi/piano/proprietary/odm/etc/init/vendor.qti.hardware.lights.service.rc:$(TARGET_COPY_OUT_ODM)/etc/init/vendor.qti.hardware.lights.service.rc \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/chre_dynamic_sensors.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/chre_dynamic_sensors.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/json.lst:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/json.lst \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/lsm6dso_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/lsm6dso_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/pakala_ccd_base.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/pakala_ccd_base.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/qmc6308_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/qmc6308_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/qsh_camera_aon_front_i_1.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/qsh_camera_aon_front_i_1.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/qsh_camera_common.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/qsh_camera_common.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/qsh_camera_imx688_6.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/qsh_camera_imx688_6.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/qsh_camera_imx688_6_actuator.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/qsh_camera_imx688_6_actuator.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/qsh_camera_ov32c4c_4.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/qsh_camera_ov32c4c_4.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sip1328.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sip1328.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sm8750_default_sensors.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8750_default_sensors.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sm8750_dynamic_sensors.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8750_dynamic_sensors.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sm8750_irq.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8750_irq.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sm8750_lsm6dso_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8750_lsm6dso_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sm8750_power_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8750_power_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sm8750_qmc6308_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8750_qmc6308_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sm8750_sip1328.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8750_sip1328.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sm8750_stk3bcx_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8750_stk3bcx_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sm8750_sx937x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sm8750_sx937x_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_amd.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_aont.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_ccd_v1_0_amd.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v1_0_amd.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_ccd_v4_0_sensors.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v4_0_sensors.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_ccd_v5_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v5_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_ccd_v5_1_te_cd_regs.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v5_1_te_cd_regs.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_ccd_v6_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v6_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_ccd_v6_0_sensors.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v6_0_sensors.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_ccd_v6_0_te_cd_regs.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_ccd_v6_0_te_cd_regs.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_cm.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_collision_detection.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_collision_detection.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_dae.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_device_orient.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_diag_filter.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_direct_channel.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_distance_bound.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_dpc.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_facing.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_flight_md.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_flight_md.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_fmv.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_geomag_rv.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_gyro_cal.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_gyro_cal_dynamic.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_gyro_cal_dynamic.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_healthy_use_of_mobile.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_healthy_use_of_mobile.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_mag_cal.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_oem_hall.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_oem_hall.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_offbody_detect_phone.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_offbody_detect_phone.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_pedometer.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_rmd.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_rotv.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_sar_algo.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_sar_algo.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_screen_down.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_screen_down.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_smd.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_tilt.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sns_transport_ppe.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sns_transport_ppe.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/stk3bcx_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/stk3bcx_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sx937x_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sx937x_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/sensors/config/sx937x_reg_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensors/config/sx937x_reg_0.json \
    vendor/xiaomi/piano/proprietary/odm/etc/vintf/manifest/vendor.qti.hardware.lights.service.xml:$(TARGET_COPY_OUT_ODM)/etc/vintf/manifest/vendor.qti.hardware.lights.service.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/init/vendor.qti.MemHal-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.MemHal-service.rc \
    vendor/xiaomi/piano/proprietary/vendor/etc/sensors/config/qsh_camera_common_sm8735.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_common_sm8735.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/sensors/config/qsh_camera_ov32c4c_4_sm8735.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_ov32c4c_4_sm8735.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/sensors/javalibs/odpmanagerlib-aar:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/javalibs/odpmanagerlib-aar \
    vendor/xiaomi/piano/proprietary/vendor/etc/sensors/sns_odp_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_odp_config \
    vendor/xiaomi/piano/proprietary/vendor/etc/vintf/manifest/mapper.qti.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/mapper.qti.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/vintf/manifest/vendor.qti.MemHal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.qti.MemHal.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/vintf/manifest/vendor.qti.hardware.display.allocator-service.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vintf/manifest/vendor.qti.hardware.display.allocator-service.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/acdbdata/Mi/Mi_acdb_cal.acdb:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Mi/Mi_acdb_cal.acdb \
    vendor/xiaomi/piano/proprietary/odm/etc/acdbdata/Mi/Mi_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Mi/Mi_workspaceFileXml.qwsp \
    vendor/xiaomi/piano/proprietary/odm/etc/acdbdata/Mi/model924_twoBlocks_eai_int8_8750.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Mi/model924_twoBlocks_eai_int8_8750.eai \
    vendor/xiaomi/piano/proprietary/odm/etc/acdbdata/Mi/model_eai_int8_8750_3blocks_00924000_xjm.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Mi/model_eai_int8_8750_3blocks_00924000_xjm.eai \
    vendor/xiaomi/piano/proprietary/odm/etc/acdbdata/Mi/model_eai_int8_8750_970k_AIoff.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Mi/model_eai_int8_8750_970k_AIoff.eai \
    vendor/xiaomi/piano/proprietary/odm/etc/acdbdata/Mi/model_eai_int8_8750__w8_b8_1000utts_v21455fre0mixdata_40w4_1220.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Mi/model_eai_int8_8750__w8_b8_1000utts_v21455fre0mixdata_40w4_1220.eai \
    vendor/xiaomi/piano/proprietary/odm/etc/acdbdata/Mi/model_eai_int8_8750__w8_b8_1000utts_v310121_55w2_0312.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Mi/model_eai_int8_8750__w8_b8_1000utts_v310121_55w2_0312.eai \
    vendor/xiaomi/piano/proprietary/odm/etc/acdbdata/Mi/model_eai_int8_8750__w8_b8_utts2000_v2820_0904.eai:$(TARGET_COPY_OUT_ODM)/etc/acdbdata/Mi/model_eai_int8_8750__w8_b8_utts2000_v2820_0904.eai \
    vendor/xiaomi/piano/proprietary/odm/etc/audio-test-config:$(TARGET_COPY_OUT_ODM)/etc/audio-test-config \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/RES1K.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/RES1K.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/audio_lowpower_app_list.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_lowpower_app_list.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/audio_module_config_primary.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/audio_module_config_primary.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/back_rcv.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/back_rcv.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/bl-spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/bl-spk.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/bl-spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/bl-spk_hp.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/bottom_spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/bottom_spk.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/bottom_spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/bottom_spk_hp.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/br-spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/br-spk.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/br-spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/br-spk_hp.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/freq_gain_O81_fs16000_M320_S90_ft32_72-nchnl-nfbin_energy_0820.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/freq_gain_O81_fs16000_M320_S90_ft32_72-nchnl-nfbin_energy_0820.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/front_rcv.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/front_rcv.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/mis_head.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/mis_head.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/mis_head_spatial.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/mis_head_spatial.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/mis_powerop_configs.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/mis_powerop_configs.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/mis_spk.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/mis_spk.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/mis_spk_spatial.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/mis_spk_spatial.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/misound_karaoke_res.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misound_karaoke_res.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/misound_karaokemix_res.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misound_karaokemix_res.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/misoundsa_spk_config.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/misoundsa_spk_config.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/null_bf_w_10t_6i_1_confer_O81Multi_2mic12_1126.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/null_bf_w_10t_6i_1_confer_O81Multi_2mic12_1126.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/null_bf_w_7t_18i_1_confer_O81Verti_2mic23_0816_2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/null_bf_w_7t_18i_1_confer_O81Verti_2mic23_0816_2.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/null_bf_w_7t_18i_1_confer_O81_2mic12_0816.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/null_bf_w_7t_18i_1_confer_O81_2mic12_0816.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/rcv.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/rcv.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/rcv_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/rcv_hp.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/rcv_seal.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/rcv_seal.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/rcv_seal_arithmetic.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/rcv_seal_arithmetic.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/sku_sun/mixer_paths_overlay_dynamic.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sku_sun/mixer_paths_overlay_dynamic.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/sku_sun/mixer_paths_overlay_static.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sku_sun/mixer_paths_overlay_static.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/sku_sun/mixer_paths_sun_mtp.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sku_sun/mixer_paths_sun_mtp.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/sku_sun/resourcemanager_sun_mtp.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sku_sun/resourcemanager_sun_mtp.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/sku_sun_qssi/audio_policy_configuration.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/sku_sun_qssi/audio_policy_configuration.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/spk.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/spk_cal_silence.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/spk_cal_silence.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/spk_hp.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/tb_spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tb_spk.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/tb_spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tb_spk_hp.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/test.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/test.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/tf_spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tf_spk.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/tf_spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tf_spk_hp.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/tgt_bf_w_17t_6i_1_confer_O81Verti_2mic23_0816_2.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/tgt_bf_w_17t_6i_1_confer_O81Verti_2mic23_0816_2.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/tgt_bf_w_17t_6i_1_confer_O81_2mic12_0816.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/tgt_bf_w_17t_6i_1_confer_O81_2mic12_0816.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/tgt_bf_w_5t_5i_1_confer_O81Multi_2mic12_1126.bin:$(TARGET_COPY_OUT_ODM)/etc/audio/tgt_bf_w_5t_5i_1_confer_O81Multi_2mic12_1126.bin \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/tl-spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tl-spk.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/tl-spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tl-spk_hp.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/top_spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/top_spk.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/top_spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/top_spk_hp.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/tr-spk.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tr-spk.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/tr-spk_hp.wav:$(TARGET_COPY_OUT_ODM)/etc/audio/tr-spk_hp.wav \
    vendor/xiaomi/piano/proprietary/odm/etc/audio/vts/audio_module_config_primary.xml:$(TARGET_COPY_OUT_ODM)/etc/audio/vts/audio_module_config_primary.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/audio_base.db:$(TARGET_COPY_OUT_ODM)/etc/audio_base.db \
    vendor/xiaomi/piano/proprietary/odm/etc/audio_policy_engine_configuration_mi.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_policy_engine_configuration_mi.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/audio_policy_engine_default_stream_volumes_mi.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_policy_engine_default_stream_volumes_mi.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/audio_policy_engine_product_strategies_mi.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_policy_engine_product_strategies_mi.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/audio_policy_engine_stream_volumes_mi.xml:$(TARGET_COPY_OUT_ODM)/etc/audio_policy_engine_stream_volumes_mi.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/touch/Pencil_Posture.xml:$(TARGET_COPY_OUT_ODM)/etc/touch/Pencil_Posture.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/touch/dynamicrate.json:$(TARGET_COPY_OUT_ODM)/etc/touch/dynamicrate.json \
    vendor/xiaomi/piano/proprietary/odm/etc/touch/gameturbotool-fastinput.json:$(TARGET_COPY_OUT_ODM)/etc/touch/gameturbotool-fastinput.json \
    vendor/xiaomi/piano/proprietary/odm/etc/touch/gameturbotool.json:$(TARGET_COPY_OUT_ODM)/etc/touch/gameturbotool.json \
    vendor/xiaomi/piano/proprietary/odm/etc/touch/stylus_game_config.json:$(TARGET_COPY_OUT_ODM)/etc/touch/stylus_game_config.json \
    vendor/xiaomi/piano/proprietary/odm/etc/df_default.xml:$(TARGET_COPY_OUT_ODM)/etc/df_default.xml \
    vendor/xiaomi/piano/proprietary/odm/etc/init.panel_info.sh:$(TARGET_COPY_OUT_ODM)/etc/init.panel_info.sh \
    vendor/xiaomi/piano/proprietary/odm/etc/init/android.hardware.weaver.rc:$(TARGET_COPY_OUT_ODM)/etc/init/android.hardware.weaver.rc \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b00 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b01 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b02 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b03 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b04 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b05 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b06 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b07 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b08 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b09 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b10 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b11 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b12 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b13 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b14 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b15 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b16 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b17 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b18 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b19 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.b20 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP.mdt \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b00:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b00 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b01:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b01 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b02:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b02 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b03:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b03 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b04:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b04 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b05:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b05 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b06:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b06 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b07:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b07 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b08:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b08 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b09:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b09 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b10:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b10 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b11:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b11 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b12:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b12 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b13:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b13 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b14:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b14 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b15:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b15 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b16:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b16 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b17:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b17 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b18:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b18 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b19:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b19 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.b20:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.b20 \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.mbn:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/CAMERA_ICP_1.mdt:$(TARGET_COPY_OUT_ODM)/firmware/CAMERA_ICP_1.mdt \
    vendor/xiaomi/piano/proprietary/odm/firmware/MCU_Upgrade.bin:$(TARGET_COPY_OUT_ODM)/firmware/MCU_Upgrade.bin \
    vendor/xiaomi/piano/proprietary/odm/firmware/MP_Setting_Criteria_59B0.csv:$(TARGET_COPY_OUT_ODM)/firmware/MP_Setting_Criteria_59B0.csv \
    vendor/xiaomi/piano/proprietary/odm/firmware/MP_Setting_Criteria_59BB.csv:$(TARGET_COPY_OUT_ODM)/firmware/MP_Setting_Criteria_59BB.csv \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b00:$(TARGET_COPY_OUT_ODM)/firmware/evass.b00 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b01:$(TARGET_COPY_OUT_ODM)/firmware/evass.b01 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b02:$(TARGET_COPY_OUT_ODM)/firmware/evass.b02 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b03:$(TARGET_COPY_OUT_ODM)/firmware/evass.b03 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b04:$(TARGET_COPY_OUT_ODM)/firmware/evass.b04 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b05:$(TARGET_COPY_OUT_ODM)/firmware/evass.b05 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b06:$(TARGET_COPY_OUT_ODM)/firmware/evass.b06 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b07:$(TARGET_COPY_OUT_ODM)/firmware/evass.b07 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b08:$(TARGET_COPY_OUT_ODM)/firmware/evass.b08 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b09:$(TARGET_COPY_OUT_ODM)/firmware/evass.b09 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b10:$(TARGET_COPY_OUT_ODM)/firmware/evass.b10 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b11:$(TARGET_COPY_OUT_ODM)/firmware/evass.b11 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b12:$(TARGET_COPY_OUT_ODM)/firmware/evass.b12 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b13:$(TARGET_COPY_OUT_ODM)/firmware/evass.b13 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b14:$(TARGET_COPY_OUT_ODM)/firmware/evass.b14 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b15:$(TARGET_COPY_OUT_ODM)/firmware/evass.b15 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b16:$(TARGET_COPY_OUT_ODM)/firmware/evass.b16 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b17:$(TARGET_COPY_OUT_ODM)/firmware/evass.b17 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b18:$(TARGET_COPY_OUT_ODM)/firmware/evass.b18 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.b19:$(TARGET_COPY_OUT_ODM)/firmware/evass.b19 \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.mbn:$(TARGET_COPY_OUT_ODM)/firmware/evass.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/evass.mdt:$(TARGET_COPY_OUT_ODM)/firmware/evass.mdt \
    vendor/xiaomi/piano/proprietary/odm/firmware/film_model.tflite:$(TARGET_COPY_OUT_ODM)/firmware/film_model.tflite \
    vendor/xiaomi/piano/proprietary/odm/firmware/fs19xx.fsm:$(TARGET_COPY_OUT_ODM)/firmware/fs19xx.fsm \
    vendor/xiaomi/piano/proprietary/odm/firmware/gen80000_zap.mbn:$(TARGET_COPY_OUT_ODM)/firmware/gen80000_zap.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/novatek_nt36532_piano_fw_boe.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_piano_fw_boe.bin \
    vendor/xiaomi/piano/proprietary/odm/firmware/novatek_nt36532_piano_fw_csot.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_piano_fw_csot.bin \
    vendor/xiaomi/piano/proprietary/odm/firmware/novatek_nt36532_piano_mp_boe.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_piano_mp_boe.bin \
    vendor/xiaomi/piano/proprietary/odm/firmware/novatek_nt36532_piano_mp_csot.bin:$(TARGET_COPY_OUT_ODM)/firmware/novatek_nt36532_piano_mp_csot.bin \
    vendor/xiaomi/piano/proprietary/odm/firmware/nvt_run_selftest_get_result_data_sample.bat:$(TARGET_COPY_OUT_ODM)/firmware/nvt_run_selftest_get_result_data_sample.bat \
    vendor/xiaomi/piano/proprietary/odm/firmware/palm_check.tflite:$(TARGET_COPY_OUT_ODM)/firmware/palm_check.tflite \
    vendor/xiaomi/piano/proprietary/odm/firmware/piano_nova_boe_thp_config.ini:$(TARGET_COPY_OUT_ODM)/firmware/piano_nova_boe_thp_config.ini \
    vendor/xiaomi/piano/proprietary/odm/firmware/piano_nova_csot_thp_config.ini:$(TARGET_COPY_OUT_ODM)/firmware/piano_nova_csot_thp_config.ini \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu30_2v.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu30_2v.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu30_2v_unsigned.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu30_2v_unsigned.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu33_4v.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu33_4v_unsigned.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu33_4v_unsigned.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu35_4v.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu35_4v.mbn \
    vendor/xiaomi/piano/proprietary/odm/firmware/vpu35_4v_unsigned.mbn:$(TARGET_COPY_OUT_ODM)/firmware/vpu35_4v_unsigned.mbn \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/DPU1010.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU1010.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/DPU10__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU10__.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/DPU11__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU11__.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/DPU12__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU12__.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/DPU9__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU9__.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/camera_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/camera_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/cpu_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/cpu_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/default_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/default_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/display_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/display_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/formats.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/formats.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/graphics_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/graphics_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/pipe_config_DPU11__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/pipe_config_DPU11__.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_1x_y1280x720.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_1x_y1280x720.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_1x_y720x1280.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_1x_y720x1280.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_2x_y1280x720.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_2x_y1280x720.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_2x_y544x960.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_2x_y544x960.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_2x_y720x1280.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_2x_y720x1280.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_2x_y960x544.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_2x_y960x544.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_3x_y384x640.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_3x_y384x640.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/sm8750_sr_3x_y640x384.dlc:$(TARGET_COPY_OUT_VENDOR)/etc/display/sm8750_sr_3x_y640x384.dlc \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/thermallevel_to_fps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/thermallevel_to_fps.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/ubwc_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/ubwc_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/display/video_alignments.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/video_alignments.json \
    vendor/xiaomi/piano/proprietary/vendor/etc/displayconfig/display_id_4630946916234099603.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630946916234099603.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/displayconfig/display_id_4630947039571902850.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630947039571902850.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/displayconfig/display_id_4630947039571902851.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630947039571902851.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/displayconfig/display_id_4630947075271898515.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_4630947075271898515.xml \
    vendor/xiaomi/piano/proprietary/vendor/etc/displayconfig/display_layout_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_layout_configuration.xml \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen70900_aqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_aqe.fw \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen70900_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_sqe.fw \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen70900_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70900_zap.mbn \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen70e00_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70e00_sqe.fw \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen70e00_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/gen70e00_zap.mbn \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen71700_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gen71700_gmu.bin \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen80000_aqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen80000_aqe.fw \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen80000_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gen80000_gmu.bin \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen80000_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/gen80000_sqe.fw \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gen80600_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gen80600_gmu.bin \
    vendor/xiaomi/piano/proprietary/vendor/firmware/gmu_gen70900.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70900.bin

PRODUCT_PACKAGES += \
    displayfeature.default \
    libMiDispDevManager \
    libadaptivehdr \
    libclient2slpi.notifier \
    libcolortempmode \
    libdisplaycount \
    libdisplaylog \
    libdither \
    libeyecare \
    libflatmode \
    libfpsmonitor \
    libhistprocess \
    libmi-stc-HW-modulate \
    libmiBrightness \
    libmiClstc \
    libmiSensorCtrl \
    libmiXmlParser \
    libmi_dspp \
    libmi_weaver \
    libmieventnodewatch \
    libpaperMode \
    librhytheyecare \
    libsdr2hdr \
    libsre \
    libtruetone \
    libvideomode \
    android.hardware.weaver.xml \
    vendor.xiaomi.hw.touchfeature-service.xml \
    android.hardware.weaver \
    vendor.xiaomi.hw.touchfeature-service \
    toucheventcheck \
    vendor.qti.hardware.lights.service \
    vendor.qti.MemHal-service
