#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/sm8750-common

PRODUCT_COPY_FILES += \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/charger_fw_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fw_fstab.qti \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/clstc_config_library.xml:$(TARGET_COPY_OUT_VENDOR)/etc/clstc_config_library.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.gatekeeper-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper-service-qti.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/android.hardware.security.keymint-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.security.keymint-service-qti.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/hlosminkdaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hlosminkdaemon.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/hw/init.batterysecret.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.batterysecret.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/hw/init.mi_thermald.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mi_thermald.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/init_thermal-engine-v2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine-v2.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/qwesd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qwesd.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/ssgtzd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ssgtzd.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.hardware.display.allocator-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.allocator-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.hardware.display.color-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.color-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.hardware.display.composer-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.display.composer-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.xiaomi.hardware.displayfeature_aidl-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.displayfeature_aidl-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/init/vendor.xiaomi.hardware.micharge-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.micharge-service.rc \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/seccomp_policy/qwesd@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qwesd@2.0.policy \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/xiaomi/sm8750-common/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/xiaomi/sm8750-common/proprietary/vendor/gpu/kbc/sequence_manifest.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/sequence_manifest.bin \
    vendor/xiaomi/sm8750-common/proprietary/vendor/gpu/kbc/unified_kbcs_32.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_kbcs_32.bin \
    vendor/xiaomi/sm8750-common/proprietary/vendor/gpu/kbc/unified_kbcs_64.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_kbcs_64.bin \
    vendor/xiaomi/sm8750-common/proprietary/vendor/gpu/kbc/unified_ksqs.bin:$(TARGET_COPY_OUT_VENDOR)/gpu/kbc/unified_ksqs.bin

PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libVkLayer_ADRENO_qprofiler \
    libq3dtools_adreno \
    libq3dtools_esx \
    libqtigatekeeper \
    mapper.qti \
    vendor.qti.hardware.qseecom@1.0-impl \
    vulkan.adreno \
    libBlAlgointf \
    libCB \
    libGPMTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libOpenCL \
    libOpenCL_adreno \
    libPeripheralStateUtils \
    libQSEEComAPI \
    libadreno_app_profiles \
    libadreno_compiler_cl \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libbacklight-calib \
    libclstc_algorithm_adapter \
    libclstc_gcp_adapter \
    libclstc_tm \
    libconfigdb \
    libdfintf \
    libdiag \
    libdigital-dimming \
    libdisp-aba \
    libdisplayconfig.qti \
    libdisplaydebug \
    libdisplayfeature \
    libdisplayfeatureservice \
    libdisplayskuutils \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdrmutils \
    libdsi_netctrl \
    libdsutils \
    libfeutils \
    libgame_enhance \
    libgpt \
    libgpu_tonemapper \
    libgralloc.qti \
    libgralloccore \
    libgrallocutils \
    libgsl \
    libhdr_backlight_adapter \
    libhdr_tm \
    libhdrdynamic \
    libhdrdynamicootf \
    libhdrvivid \
    libhistogram \
    libidl \
    libintervmipc \
    libkcl \
    libkernelmanager \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    libllvm-glnext \
    libllvm-qcom \
    libllvm-qgl \
    liblmthermallistner \
    libmapperutils \
    libmdmdetect \
    libmemutils \
    libminkdescriptor \
    libminksocket_vendor \
    libmisight \
    libnicm \
    libnicm_dsi \
    libnicm_utils \
    libops \
    libperipheral_client \
    libqcbor \
    libqdMetaData \
    libqdcm-algo \
    libqdcm-json-mode-parser \
    libqdcm-mode-parser \
    libqdi \
    libqdutils \
    libqisl \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqrtr \
    libqseed3 \
    libqservice \
    libqspm-mem-utils-vendor \
    libqtikeymaster4 \
    libqtikeymint \
    librcmask \
    librpmb \
    libsdedrm \
    libsdm-color \
    libsdm-disp-vndapis \
    libsdmclient \
    libsdmcore \
    libsdmdal \
    libsdmutils \
    libseclog \
    libsnapdragoncolor-manager \
    libsnapdragoncolor-qdcm \
    libspl \
    libssd \
    libtestutils \
    libthermalclient \
    libtime_genoff \
    libtinyxml2_1 \
    libvmfilexfer \
    libvmmem \
    libxml \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.qti.hardware.display.snapalloc-impl \
    vendor.qti.hardware.dsp-V1-ndk \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.qseecom-V1-ndk \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.qspmhal-V1-ndk \
    vendor.xiaomi.hardware.display.mihwcextension-V1-ndk \
    vendor.xiaomi.hardware.displayfeature@1.0 \
    vendor.xiaomi.hardware.displayfeature_aidl-V2-ndk \
    vendor.xiaomi.hardware.micharge-V2-ndk \
    vendor.xiaomi.hw.touchfeature-V1-ndk \
    vendor.xiaomi.sensor.citsensorservice-V1-ndk \
    com.qualcomm.qti.gpudrivers.sun.api35 \
    android.hardware.security.keymint-service-qti.xml \
    vendor.qti.hardware.qseecom@1.0-service.xml \
    vendor.xiaomi.hardware.displayfeature_aidl-service.xml \
    vendor.xiaomi.hardware.micharge.xml \
    adsprpcd \
    batterysecret \
    displayfeature \
    hlosminkdaemon \
    android.hardware.gatekeeper-service-qti \
    android.hardware.security.keymint-service-qti \
    vendor.qti.hardware.display.allocator-service \
    vendor.qti.hardware.display.color-service \
    vendor.qti.hardware.display.composer-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.xiaomi.hardware.displayfeature_aidl-service \
    vendor.xiaomi.hardware.micharge-service \
    mi_thermald \
    pm-proxy \
    pm-service \
    ppd \
    qdcmss \
    qseecomd \
    qwesd \
    ssgtzd \
    system_dlkm_modprobe \
    thermal-engine-v2 \
    vendor_modprobe
